version: '3.4'

services:
  daas.ui.blazor:
    image: mmercan/daas-ui-blazor-core:${TAGVersion}
    build:
      context: .
      dockerfile: ./src/DaaS.UI.Blazor/Dockerfile
    ports:
      - "8080"