version: '3.4'

services:
  daas.k8s.worker.controller:
    image: mmercan/daask8sworkercontroller-core:${TAGVersion}
    build:
      context: .
      dockerfile: src/DaaS.K8s.Worker.Controller/Dockerfile

