name: CaaS K8s Controller

on:
  push:
    branches: [main, features/*]
    paths:
      - src/CaaS.K8s.Worker.Controller/**
      - .github/workflows/controller-build.yml
      - devops/deploy/helm/caas-k8s-worker-controller/**
  pull_request:
    branches: [main, features/*]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      dockercomposeLoc: docker-compose.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: View Docker Compose config
        run: |
          export TAGVersion=01
          export DOCKER_REGISTRY=mmercan
          docker-compose --file $dockercomposeLoc --log-level DEBUG config

      - name: Build Docker Image
        run: |
          export TAGVersion=01
          export DOCKER_REGISTRY=mmercan
          docker-compose --file $dockercomposeLoc --log-level DEBUG build

      - name: tag Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker tag "${image}":"01-prod-linux" "${image}":"$GITHUB_RUN_ID"
            docker tag "${image}":"01-prod-linux" "${image}":"latest"
          done

      - name: list Images
        run: |
          docker images

      - name: Push Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker image push --all-tags ${image}
          done

  helmRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: custom packaging
        run: |
          VERSION=v0.1.0
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package devops/deploy/helm/caas-k8s-worker-controller --app-version=${VERSION:1} --version=${VERSION:1} --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          charts_dir: devops/deploy/helm
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      chartName: "sentinel-api-healthmonitoring"
      namespace: "sentinel-healthcheck"
      releaseName: "sentinel-api-healthmonitoring-dev"
      pipelines_pipeline: '"${{ github.WORKFLOW }}"'
      pipelines_run: ${{ github.RUN_ID }}
      pipelines_org: '"${{ github.SERVER_URL }}"'
      pipelines_repo: ${{ github.repository }}
      pipelines_gitsha: ${{ github.sha }}
      pipelines_branch: ${{ github.ref }}
      pipelines_runuri: '"${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }}"'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-aks

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: Check Helm Version
        run: |
          helm version

      - name: Helm Package
        run: |
          helm package --version 2.0.0-$GITHUB_RUN_ID --destination /home/runner/work/_temp ./devops/deploy/Helm/sentinel-healthcheck/charts/$chartName

      - name: Validate Helm Package
        run: |
          helm template "./devops/deploy/Helm/sentinel-healthcheck/charts/$chartName" -f "./devops/deploy/Helm/values/$chartName/dev-values.yaml"

      - name: Helm upgrade
        run: |
          helm upgrade --namespace $namespace --install \
          --history-max 1 \
          --values ./devops/deploy/Helm/values/$chartName/dev-values.yaml \
          --set image.tag=$GITHUB_RUN_ID \
          --set branch=master \
          --wait $releaseName \
          /home/runner/work/_temp/$chartName-2.0.0-$GITHUB_RUN_ID.tgz \
