name: CaaS K8s Controller

on:
  push:
    tags:
      - "*"
    paths:
      - src/CaaS.K8s.Worker.Controller/**
      - .github/workflows/controller-build.yml
      - devops/deploy/helm/caas-k8s-worker-controller/**
  pull_request:
    branches: [main, features/*]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      dockercomposeLoc: docker-compose.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: View Docker Compose config
        run: |
          export TAGVersion=${{github.ref_name}}
          export DOCKER_REGISTRY=mmercan
          docker-compose --file $dockercomposeLoc --log-level DEBUG config

      - name: Build Docker Image
        run: |
          export TAGVersion=${{github.ref_name}}
          export DOCKER_REGISTRY=mmercan
          docker-compose --file $dockercomposeLoc --log-level DEBUG build

      - name: tag Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker tag "${image}":"${{github.ref_name}}" "${image}":"$GITHUB_RUN_ID"
            docker tag "${image}":"${{github.ref_name}}" "${image}":"latest"
          done

      - name: list Images
        run: |
          docker images

      - name: Push Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker image push --all-tags ${image}
          done

  helmRelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: custom packaging
        run: |
          VERSION=${{github.ref_name}}
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts/caas-k8s-worker-controller --app-version=${VERSION:1} --version=${VERSION:1} --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        # with:
        #   skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
