name: DaaS UI Blazor Build

on:
  push:
    tags:
      - "*"
    paths:
      - src/DaaS.UI.Blazor/**
      - .github/workflows/daas-ui-blazor-build.yml
      - devops/deploy/helm/daas-k8s-worker-controller/**
  pull_request:
    branches: [main, features/*]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      dockercomposeLoc: docker-compose-blazor.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: View Docker Compose config
        run: |
          export TAGVersion=${{github.ref_name}}
          export DOCKER_REGISTRY=mmercan
          docker compose --file $dockercomposeLoc --log-level DEBUG config

      - name: Build Docker Image
        run: |
          export TAGVersion=${{github.ref_name}}
          export DOCKER_REGISTRY=mmercan
          docker compose --file $dockercomposeLoc --log-level DEBUG build

      - name: tag Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker tag "${image}":"${{github.ref_name}}" "${image}":"$GITHUB_RUN_ID"
            docker tag "${image}":"${{github.ref_name}}" "${image}":"latest"
          done

      - name: list Images
        run: |
          docker images

      - name: Push Images
        run: |
          images=$(cat $dockercomposeLoc | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker image push --all-tags ${image}
          done
