# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install SonarCloud scanners
      run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: login for MSI
      run: |
          az version
          az login --service-principal -t $Tenant_ID -u $Client_ID -p $Client_Secret
      shell: bash
      env:
        Tenant_ID  : ${{secrets.Tenant_ID}}   
        Client_ID  : ${{secrets.Client_ID}}   
        Client_Secret  : ${{secrets.Client_Secret}}   
    - name: print secrets
      run: |
          echo $DEV_ENV_FILE >> tests/Sentinel.NetworkUtils.Tests/appsettings.json
          cat tests/Sentinel.NetworkUtils.Tests/appsettings.json
      shell: bash
      env:
        DEV_ENV_FILE : ${{secrets.APPSETTINGS}}
    
    - name: Restore dependencies
      run: dotnet restore Sentinel.K8.DaaS.sln
    - name: Build
      run: dotnet build Sentinel.K8.DaaS.sln --no-restore
    - name: Test
      run: dotnet test Sentinel.K8.DaaS.sln --collect "Code Coverage" --no-build --verbosity normal

